In [1]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Data_sets\\messy_sales_data.csv")
df.head()

,Order ID,Date,Salesperson,Region,Product,Quantity,Unit Price
0,ORD7439,2026-01-25,Nisha Kumari,North,Printer,8.0,8000.0
1,ORD9059,2026-03-23,Bhavana Rao,East,Speakers,1.0,3000.0
2,ORD0569,2026-01-01,Ananya Singh,South,Mouse,5.0,600.0
3,ORD9345,2026-01-19,Shreya Ghosh,South,Headphones,7.0,2500.0
4,ORD2237,2026-02-24,Siddharth Khanna,East,Mobile,1.0,20000.0

In [2]:
print(pd.isnull(df))
print("\nMissing values per column:")
print(df.isnull().sum())

       Order ID   Date  Salesperson  Region  Product  Quantity  Unit Price
0         False  False        False   False    False     False       False
1         False  False        False   False    False     False       False
2         False  False        False   False    False     False       False
3         False  False        False   False    False     False       False
4         False  False        False   False    False     False       False
...         ...    ...          ...     ...      ...       ...         ...
10005     False  False        False   False    False     False       False
10006     False  False        False   False    False     False       False
10007     False  False        False   False    False     False       False
10008     False  False        False   False    False     False       False
10009     False  False        False   False    False     False       False

[10010 rows x 7 columns]

Missing values per column:
Order ID       0
Date           5
Salesperson    8
Region         5
Product        5
Quantity       5
Unit Price     5
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(10)

In [6]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()
df.to_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Data_sets\\cleaned_sales_data.csv", index=False)
print("Cleaned sales dataset saved!")
print("Total rows after removing duplicates:", len(df))
print("\nMissing values per column after cleaning:")
print(df.isnull().sum())
print("\nFirst 10 rows after cleaning:")
print(df.head(10))

Cleaned sales dataset saved!
Total rows after removing duplicates: 10000

Missing values per column after cleaning:
Order ID       0
Date           5
Salesperson    8
Region         5
Product        5
Quantity       5
Unit Price     5
dtype: int64

First 10 rows after cleaning:
  Order ID        Date       Salesperson Region     Product  Quantity  \
0  ORD7439  2026-01-25      Nisha Kumari  North     Printer       8.0
1  ORD9059  2026-03-23       Bhavana Rao   East    Speakers       1.0
2  ORD0569  2026-01-01      Ananya Singh  South       Mouse       5.0
3  ORD9345  2026-01-19      Shreya Ghosh  South  Headphones       7.0
4  ORD2237  2026-02-24  Siddharth Khanna   East      Mobile       1.0
5  ORD3058  2026-02-07    Siddharth Jain  North    Keyboard       7.0
6  ORD7507  2026-03-05    Rohan Kulkarni  North      Mobile       1.0
7  ORD1497  2026-02-04       Nikhil Jain   East      Mobile       9.0
8  ORD1796  2026-03-02       Rahul Verma  South     Monitor       7.0
9  ORD7854  2026-01-10       Bhavana Rao  South  Smartwatch       6.0

   Unit Price
0      8000.0
1      3000.0
2       600.0
3      2500.0
4     20000.0
5      1200.0
6     20000.0
7     20000.0
8     12000.0
9     10000.0

In [7]:
print(df.isnull().sum())
print("\nTotal rows after cleaning:", len(df))

Order ID       0
Date           5
Salesperson    8
Region         5
Product        5
Quantity       5
Unit Price     5
dtype: int64

Total rows after cleaning: 10000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isna().sum()

Order ID       0
Date           5
Salesperson    8
Region         5
Product        5
Quantity       5
Unit Price     5
dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 10009
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     10000 non-null  str
 1   Date         9995 non-null   str
 2   Salesperson  9992 non-null   str
 3   Region       9995 non-null   str
 4   Product      9995 non-null   str
 5   Quantity     9995 non-null   float64
 6   Unit Price   9995 non-null   float64
dtypes: float64(2), str(5)
memory usage: 625.0 KB

In [11]:
null_rows = df[df.isnull().any(axis=1)]

In [12]:
print(null_rows)

     Order ID        Date      Salesperson Region              Product  \
215   ORD7323  2026-01-14      Priya Reddy  North           Headphones
441   ORD4439  2026-03-05    Sandeep Yadav  North               Camera
1107  ORD5649         NaN     Ananya Singh   West             Speakers
1178  ORD9899  2026-01-19   Harish Chandra  North               Mobile
1425  ORD9424  2026-02-02       Meera Iyer   East               Tablet
1543  ORD1528  2026-03-25              NaN  North               Tablet
2744  ORD7157         NaN       Tanvi Shah  South               Laptop
2831  ORD7992  2026-02-21              NaN  North             Keyboard
2885  ORD4519  2026-03-23     Sanjay Patel   East               Tablet
3603  ORD5099  2026-01-26   Shalini Kapoor  North  External Hard Drive
3838  ORD1175  2026-03-24      Rahul Verma   East                  NaN
5361  ORD1706  2026-01-10     Naveen Kumar   East               Camera
5364  ORD1494  2026-01-10      Nikhil Jain   East               Camera
5366  ORD7277  2026-03-25  Gaurav Malhotra   West                  NaN
5529  ORD0499  2026-03-14    Sahana Murthy    NaN           Headphones
5760  ORD7900  2026-03-24              NaN   East              Monitor
6183  ORD3564  2026-03-18       Ishita Roy  South                  NaN
6237  ORD6309  2026-01-10              NaN  South               Mobile
6262  ORD8306         NaN     Rajesh Kumar   West             Speakers
6285  ORD0973  2026-02-04              NaN  South               Tablet
6304  ORD2793  2026-01-02      Pranav Shah    NaN           Headphones
6689  ORD6579  2026-02-16     Yash Agarwal  South             Keyboard
6925  ORD8821  2026-03-12     Vikram Singh  South                  NaN
6953  ORD1801  2026-02-28     Nisha Kumari  South                  NaN
7370  ORD8317         NaN   Deepak Chauhan  South                Mouse
7388  ORD8462  2026-03-21      Ajay Thakur   East               Camera
8375  ORD7176  2026-01-12              NaN  South                Mouse
8684  ORD0975  2026-02-02        Kavya Rao    NaN             Speakers
8768  ORD4279  2026-01-23              NaN   East           Headphones
8917  ORD0805  2026-01-07              NaN   East           Smartwatch
9022  ORD8394  2026-03-20       Shreya Das    NaN             Speakers
9211  ORD6289         NaN      Neha Sharma  South           Smartwatch
9722  ORD5601  2026-01-10       Mohan Babu    NaN               Laptop

      Quantity  Unit Price
215        NaN      2500.0
441        8.0         NaN
1107      10.0      3000.0
1178       7.0         NaN
1425       7.0         NaN
1543       8.0     15000.0
2744       8.0     45000.0
2831       5.0      1200.0
2885       NaN     15000.0
3603       NaN      5000.0
3838      10.0      5000.0
5361       NaN     18000.0
5364       2.0         NaN
5366       2.0      3000.0
5529       1.0      2500.0
5760       4.0     12000.0
6183       7.0       600.0
6237       8.0     20000.0
6262       8.0      3000.0
6285       3.0     15000.0
6304       3.0      2500.0
6689      10.0         NaN
6925       9.0      5000.0
6953       6.0      3000.0
7370      10.0       600.0
7388       NaN     18000.0
8375       6.0       600.0
8684      10.0      3000.0
8768       2.0      2500.0
8917       1.0     10000.0
9022       2.0      3000.0
9211       4.0     10000.0
9722       1.0     45000.0

In [13]:
df['Salesperson'].isna().sum()
df.dropna(subset=['Salesperson'], inplace=True)

In [14]:
df['Salesperson'].isna().sum()

np.int64(0)

In [15]:
df['Product'].isna().sum()
df.dropna(subset=['Product'], inplace=True)

In [16]:
df['Product'].isna().sum()

np.int64(0)

In [17]:
df["Date"] = df["Date"].ffill(inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_8108\3551486543.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Date"] = df["Date"].ffill(inplace=True)

In [18]:
df['Date'].isna().sum()

np.int64(0)

In [19]:
df["Region"] = df["Region"].bfill(inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_8108\706944095.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Region"] = df["Region"].bfill(inplace=True)

In [20]:
df['Region'].isna().sum()

np.int64(0)

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 9987 entries, 0 to 10009
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9987 non-null   str
 1   Date         9987 non-null   str
 2   Salesperson  9987 non-null   str
 3   Region       9987 non-null   str
 4   Product      9987 non-null   str
 5   Quantity     9982 non-null   float64
 6   Unit Price   9982 non-null   float64
dtypes: float64(2), str(5)
memory usage: 624.2 KB

In [22]:
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_8108\3651752953.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean(), inplace=True)

In [23]:
df.dropna(inplace=True)

In [24]:
df.describe()

          Quantity    Unit Price
count  9982.000000   9982.000000
mean      5.545254  11871.037868
std       2.866006  12037.496593
min      -1.000000      0.000000
25%       3.000000   3000.000000
50%       6.000000  10000.000000
75%       8.000000  18000.000000
max      10.000000  45000.000000

In [25]:
df.isnull().sum()

Order ID       0
Date           0
Salesperson    0
Region         0
Product        0
Quantity       0
Unit Price     0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 9982 entries, 0 to 10009
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9982 non-null   str
 1   Date         9982 non-null   str
 2   Salesperson  9982 non-null   str
 3   Region       9982 non-null   str
 4   Product      9982 non-null   str
 5   Quantity     9982 non-null   float64
 6   Unit Price   9982 non-null   float64
dtypes: float64(2), str(5)
memory usage: 623.9 KB

In [27]:
df.to_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Data_Cleaning_done_here\\cleaned_data.csv", index=False)